import type { Metadata } from 'next';
import 'nhsuk-frontend/dist/nhsuk/index.scss';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning>
        <script>
          document.body.className += ' js-enabled' + ('noModule' in HTMLScriptElement.prototype ? '
          nhsuk-frontend-supported' : '');
        </script>
        {children}
      </body>
    </html>
  );
}
